# Generated by Django 5.0.4 on 2024-05-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_keeper', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='img',
            field=models.CharField(default='', max_length=2000000),
        ),
    ]
