# Generated by Django 5.0.4 on 2024-05-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_keeper', '0002_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.CharField(max_length=200)),
            ],
        ),
    ]
