# Generated by Django 5.0.4 on 2024-05-06 19:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_keeper', '0003_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
