# Generated by Django 5.0.6 on 2024-05-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_keeper', '0005_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='unsplash_url',
            field=models.CharField(default='default_val', max_length=500),
        ),
    ]
