# Generated by Django 5.0.4 on 2024-05-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_keeper', '0005_alter_setting_bio_alter_setting_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='setting',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='setting',
            name='gender',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='setting',
            name='sex',
            field=models.CharField(max_length=100),
        ),
    ]
