# Generated by Django 5.0.4 on 2024-05-06 23:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_keeper', '0006_alter_setting_bio_alter_setting_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='email',
            field=models.EmailField(max_length=100, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='setting',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-Binary'), ('transgender_male', 'Transgender Male'), ('transgender_female', 'Transgender Female'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='setting',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('intersex', 'Intersex'), ('non_binary', 'Non-Binary'), ('other', 'Other')], max_length=20),
        ),
    ]
