# Generated by Django 5.0.6 on 2024-05-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_keeper', '0007_remove_recipe_unsplash_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='img',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
